server:
  port: 8080

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: 'cm9vdA=='

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:h2:mem:healthyme;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: admin
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    contexts: dev, faker
    change-log: classpath:config/liquibase/master.xml
  mail:
    host: localhost
    port: 1025
    username:
    password:
  messages:
    cache-duration: PT1S
  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.core: DEBUG
    org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter: DEBUG
    org.springframework.web: DEBUG
    tech.jhipster: DEBUG
