databaseChangeLog:
  - changeSet:
      id: 20250902-01-rename-examination-record-date
      author: you
      changes:
        - renameColumn:
            tableName: examination_record
            oldColumnName: date
            newColumnName: exam_date
            columnDataType: date
