package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExaminationCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExaminationCategoryAllPropertiesEquals(ExaminationCategory expected, ExaminationCategory actual) {
        assertExaminationCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertExaminationCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExaminationCategoryAllUpdatablePropertiesEquals(ExaminationCategory expected, ExaminationCategory actual) {
        assertExaminationCategoryUpdatableFieldsEquals(expected, actual);
        assertExaminationCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExaminationCategoryAutoGeneratedPropertiesEquals(ExaminationCategory expected, ExaminationCategory actual) {
        assertThat(actual)
            .as("Verify ExaminationCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExaminationCategoryUpdatableFieldsEquals(ExaminationCategory expected, ExaminationCategory actual) {
        assertThat(actual)
            .as("Verify ExaminationCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExaminationCategoryUpdatableRelationshipsEquals(ExaminationCategory expected, ExaminationCategory actual) {
        // empty method
    }
}
