package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VisitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitAllPropertiesEquals(Visit expected, Visit actual) {
        assertVisitAutoGeneratedPropertiesEquals(expected, actual);
        assertVisitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitAllUpdatablePropertiesEquals(Visit expected, Visit actual) {
        assertVisitUpdatableFieldsEquals(expected, actual);
        assertVisitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitAutoGeneratedPropertiesEquals(Visit expected, Visit actual) {
        assertThat(actual)
            .as("Verify Visit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitUpdatableFieldsEquals(Visit expected, Visit actual) {
        assertThat(actual)
            .as("Verify Visit relevant properties")
            .satisfies(a -> assertThat(a.getVisitDate()).as("check visitDate").isEqualTo(expected.getVisitDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitUpdatableRelationshipsEquals(Visit expected, Visit actual) {
        assertThat(actual)
            .as("Verify Visit relationships")
            .satisfies(a -> assertThat(a.getDoctor()).as("check doctor").isEqualTo(expected.getDoctor()));
    }
}
